"""phase_7_reports

Revision ID: e9b41a87c123
Revises: 66055f64a1c1
Create Date: 2026-09-16 16:05:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e9b41a87c123'
down_revision: Union[str, None] = '66055f64a1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types if needed in postgresql, or fallback
    bind = op.get_bind()
    is_postgres = bind.dialect.name == 'postgresql'

    if is_postgres:
        report_format_enum = postgresql.ENUM('PDF', 'CSV', name='reportformat', create_type=False)
        report_status_enum = postgresql.ENUM('QUEUED', 'GENERATING', 'COMPLETED', 'FAILED', name='reportstatus', create_type=False)
        # Create types manually if they don't exist
        op.execute(sa.text("DO $$ BEGIN CREATE TYPE reportformat AS ENUM ('PDF', 'CSV'); EXCEPTION WHEN duplicate_object THEN null; END $$;"))
        op.execute(sa.text("DO $$ BEGIN CREATE TYPE reportstatus AS ENUM ('QUEUED', 'GENERATING', 'COMPLETED', 'FAILED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"))
    else:
        report_format_enum = sa.Enum('PDF', 'CSV', name='reportformat')
        report_status_enum = sa.Enum('QUEUED', 'GENERATING', 'COMPLETED', 'FAILED', name='reportstatus')

    op.create_table(
        'reports',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('project_id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('format', report_format_enum, nullable=False),
        sa.Column('status', report_status_enum, nullable=False),
        sa.Column('storage_path', sa.String(), nullable=True),
        sa.Column('error', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
