"""Phase 5 models

Revision ID: 1d8e9a001c32
Revises: bcea0ad4e0af
Create Date: 2026-09-16 15:29:09.708953+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1d8e9a001c32'
down_revision: Union[str, None] = 'bcea0ad4e0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('design_item_id', sa.Uuid(), nullable=True),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('ack_item_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('MATCHED', 'MISSING', 'EXTRA', 'CHANGED', 'UNCERTAIN', name='matchgroupstatus', create_type=False), nullable=False),
    sa.Column('final_sku', sa.String(), nullable=True),
    sa.Column('final_quantity', sa.Integer(), nullable=True),
    sa.Column('final_dimensions', sa.JSON(), nullable=True),
    sa.Column('final_finish', sa.String(), nullable=True),
    sa.Column('final_door_style', sa.String(), nullable=True),
    sa.Column('final_modifications', sa.JSON(), nullable=True),
    sa.Column('final_price', sa.String(), nullable=True),
    sa.Column('final_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ack_item_id'], ['canonical_line_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['design_item_id'], ['canonical_line_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['canonical_line_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discrepancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('match_group_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('source_values', sa.JSON(), nullable=False),
    sa.Column('comparison_values', sa.JSON(), nullable=False),
    sa.Column('introduced_at', postgresql.ENUM('DESIGN', 'ORDER', 'ACKNOWLEDGEMENT', name='documenttype', create_type=False), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', postgresql.ENUM('CRITICAL', 'WARNING', 'INFO', name='severity', create_type=False), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_group_id'], ['match_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discrepancies')
    op.drop_table('match_groups')
    # ### end Alembic commands ###
